import { useEffect, useState } from 'react'
import { bytesLabel } from './replayFiles'

export type SubmissionHandoff = { paths: string[]; opponent: string; mode: 'normal' | 'rehost'; submission: string }
type API = <T>(path: string, method?: string, body?: unknown) => Promise<T>
type Folder = { id: string; name: string; disposition: string | null; path?: string; map?: string; rounds?: number; match_type?: string; score?: number[]; our_score?: number|null; their_score?: number|null; tracked_count?: number; eligible?: boolean; rehost_eligible?: boolean; duplicate?: boolean; status?: string }
type Submission = { id: string; display_id: string; team_slug: string; team_name: string; season_slug: string; season_name: string; opponent: string; match_date: string; submitter: string; discord: string; rehost: string; notes: string; status: string; folders: Folder[]; objects_deleted_at: number | null; actual_bytes: number; submitted_at: number | null }
type Storage = { configured: boolean; message?: string; enabled: boolean; stored_bytes: number; reserved_bytes: number; cap_bytes: number; pending_bytes: number; terminal_bytes: number; pending_count: number; percent: number; last_reconciled: number | null }

export function SubmissionsPage({ api, teams, seasons, handoff, changed }: { api: API; teams: { id: number; slug: string; name: string; active: number }[]; seasons: { slug: string; name: string; active: number }[]; handoff: (value: SubmissionHandoff, team: number, season: string) => void; changed: (count: number) => void }) {
  const [storage, setStorage] = useState<Storage | null>(null), [items, setItems] = useState<Submission[]>([]), [all, setAll] = useState(false)
  const [detail, setDetail] = useState<Submission | null>(null), [folders, setFolders] = useState<Folder[]>([]), [selected, setSelected] = useState<string[]>([])
  const [team, setTeam] = useState(''), [season, setSeason] = useState(''), [mode, setMode] = useState<'normal' | 'rehost'>('normal')
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false), [reason, setReason] = useState(''), [notes, setNotes] = useState('')
  async function load() { const [s, list] = await Promise.all([api<Storage>('/submissions/storage'), api<Submission[]>('/submissions?status=' + (all ? 'all' : 'pending'))]); setStorage(s); setItems(list); changed(s.pending_count || 0) }
  useEffect(() => { void load().catch(e => setError(e.message)) }, [all])
  async function action(work: () => Promise<void>) { setBusy(true); setError(''); setNotice(''); try { await work() } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  async function open(id: string) { const s = await api<Submission>('/submissions/' + id); setDetail(s); setFolders([]); setSelected([]); setReason(''); setNotes(''); setTeam(String(teams.find(t => t.slug === s.team_slug && t.active)?.id || '')); setSeason(seasons.find(p => p.slug === s.season_slug)?.slug || seasons.find(p => p.active)?.slug || ''); setMode('normal') }
  async function inspect() { if (!detail) return; await api('/submissions/' + detail.id + '/stage', 'POST', {}); const result = await api<{ folders: Folder[] }>('/submissions/' + detail.id + '/inspect', 'POST', { team_id: Number(team), season_slug: season }); setFolders(result.folders); setSelected([]); await load() }
  const chosen = folders.filter(f => selected.includes(f.id))
  return <><div className="admin-heading"><div><span className="eyebrow">PRIVATE REPLAY INBOX</span><h1>Submissions</h1><p>Review submitted folders locally before explicitly importing them as NECC.</p></div><button className="admin-button secondary" disabled={busy} onClick={() => void action(load)}>Refresh</button></div>
    {error && <div className="admin-inline-error" role="alert">{error}</div>}{notice && <div className="admin-notice success" role="status">{notice}</div>}
    {storage?.configured ? <section className="admin-panel"><h2>Cloud storage · {storage.percent.toFixed(1)}%</h2><p>Stored {bytesLabel(storage.stored_bytes)} · Reserved {bytesLabel(storage.reserved_bytes)} · Cap {bytesLabel(storage.cap_bytes)}</p><p>Pending {bytesLabel(storage.pending_bytes)} · Imported/rejected {bytesLabel(storage.terminal_bytes)} · {storage.pending_count} awaiting review</p>{storage.percent >= 75 && <p className="negative">Storage warning: {storage.percent >= 100 ? '100%' : storage.percent >= 95 ? '95%' : storage.percent >= 85 ? '85%' : '75%'} threshold reached. Intake stops at the cap.</p>}<p>Last reconciliation: {storage.last_reconciled ? new Date(storage.last_reconciled * 1000).toLocaleString() : 'Not yet run'}. Terminal files are retained seven days; pending files never expire.</p><div className="admin-actions">
      <button className="admin-button secondary" disabled={busy} onClick={() => void action(async () => { let result: { complete: boolean }; do { result = await api('/submissions/reconcile', 'POST', {}) } while (!result.complete); await load(); setNotice('Actual R2 storage reconciled.') })}>Reconcile storage</button>
      <button className="admin-button secondary" disabled={busy} onClick={() => void action(async () => { await api('/submissions/cleanup', 'POST', {}); await load(); setNotice('Expired upload sessions and eligible terminal files cleaned.') })}>Run retention cleanup</button>
      <button className="admin-button secondary" disabled={busy} onClick={() => void action(async () => { await api('/submissions/options', 'POST', {}); setNotice('Public team and active season choices synchronized.') })}>Sync team/season choices</button>
      <button className="admin-button" disabled={busy} onClick={() => void action(async () => { await api('/submissions/settings', 'POST', { enabled: !storage.enabled }); await load() })}>{storage.enabled ? 'Disable public submissions' : 'Enable public submissions'}</button>
    </div></section> : <div className="admin-empty">{storage?.message || 'Loading private inbox…'}</div>}
    <label><input type="checkbox" checked={all} onChange={e => setAll(e.target.checked)} disabled={busy}/> Include reviewed submissions</label>
    <section className="admin-panel"><h2>Replay submissions</h2>{!items.length && <p>No submissions in this view.</p>}{items.map(s => <div className="activity-row" key={s.id}><span><b>{s.display_id} · {s.team_name} vs {s.opponent}</b><small>{s.season_name} · {s.match_date} · {s.submitter} · {s.folders.length} folders · {bytesLabel(s.actual_bytes)} · Rehost: {s.rehost==='unsure'?'Not sure':s.rehost} · {s.discord&&'Discord: '+s.discord+' · '}{s.submitted_at&&new Date(s.submitted_at*1000).toLocaleString()} · {s.status}</small></span><button className="admin-button secondary" disabled={busy} onClick={() => void action(() => open(s.id))}>Review</button></div>)}</section>
    {detail && <section className="admin-panel"><h2>{detail.display_id} · {detail.status}</h2><p><b>Submitted as:</b> {detail.team_name} · {detail.season_name} · vs {detail.opponent} · {detail.match_date}</p><p>Submitted by {detail.submitter}{detail.discord && ' · Discord: ' + detail.discord}. Rehost: {detail.rehost}</p><p>{detail.folders.length} replay folders · {bytesLabel(detail.actual_bytes)}</p><p>Private submitter notes: {detail.notes || 'None'}</p>
      {['pending', 'reviewing'].includes(detail.status) && <><div className="admin-form-grid"><label>Importing as team<select value={team} onChange={e => { setTeam(e.target.value); setFolders([]); setSelected([]) }}><option value="">Choose a team</option>{teams.filter(t => t.active).map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Importing into season<select value={season} onChange={e => { setSeason(e.target.value); setFolders([]); setSelected([]) }}><option value="">Choose a season</option>{seasons.map(s => <option key={s.slug} value={s.slug}>{s.name}</option>)}</select></label></div>
        <button className="admin-button" disabled={busy || !team || !season} onClick={() => void action(inspect)}>Download, verify & inspect locally</button>
        <p>Inspection uses the existing trusted local parser. Uploading or downloading does not import statistics.</p>
        {folders.map(f => <label className="activity-row" key={f.id}><input type="checkbox" disabled={busy || !!detail.folders.find(row => row.id === f.id)?.disposition || !f.path || (mode === 'normal' ? !f.eligible : !f.rehost_eligible)} checked={selected.includes(f.id)} onChange={e => setSelected(e.target.checked ? [...selected, f.id] : selected.filter(id => id !== f.id))}/><span><b>{f.name} · {f.map || 'Unknown map'}</b><small>{f.rounds ?? '—'} rounds · {f.our_score!=null?`${teams.find(t=>t.id===Number(team))?.name} ${f.our_score}–${f.their_score}`:f.score?`Team 0: ${f.score[0]} / Team 1: ${f.score[1]}`:'—'} · {f.match_type} · {f.tracked_count ?? 0} roster matches · {f.status}{f.duplicate&&' · duplicate already imported'}{detail.folders.find(row => row.id === f.id)?.disposition && ' · already resolved'}</small></span></label>)}
        {!!folders.length && <><label>Review selected folders as<select value={mode} onChange={e => { setMode(e.target.value as 'normal' | 'rehost'); setSelected([]) }}><option value="normal">One normal map</option><option value="rehost">Segments of one rehosted map</option></select></label><button className="admin-button" disabled={busy || (mode === 'normal' ? chosen.length !== 1 : chosen.length < 2)} onClick={() => handoff({ paths: chosen.map(f => f.path!), opponent: detail.opponent, mode, submission: detail.display_id }, Number(team), season)}>Open existing import review</button><p>Normal maps are imported one at a time. Rehost segments require the existing round exclusions, ordering, roster and score confirmations. Submitted notes remain private.</p></>}
        <label>Rejection reason<input value={reason} maxLength={240} onChange={e => setReason(e.target.value)}/></label><label>Private admin notes<textarea value={notes} maxLength={2000} onChange={e => setNotes(e.target.value)}/></label><button className="admin-button secondary" disabled={busy || !reason.trim()} onClick={() => { if (window.confirm('Reject all remaining unconsumed folders? Existing local imports remain intact.')) void action(async () => { await api('/submissions/' + detail.id + '/reject', 'POST', { reason, notes }); await open(detail.id); await load() }) }}>Reject remaining folders</button>
      </>}
      <button className="admin-button secondary" disabled={busy} onClick={() => void action(async () => { await api('/submissions/' + detail.id + '/sync', 'POST', {}); await open(detail.id); await load(); setNotice('Local archive receipts synchronized.') })}>Retry cloud status sync</button>
      {['imported', 'rejected', 'failed'].includes(detail.status) && !detail.objects_deleted_at && <button className="admin-button secondary" disabled={busy} onClick={() => { const confirmation = window.prompt('Delete terminal cloud copies now? Local archived replays are preserved. Type ' + detail.display_id); if (confirmation === detail.display_id) void action(async () => { await api('/submissions/' + detail.id + '/purge', 'POST', { confirm_display_id: confirmation }); await open(detail.id); await load() }) }}>Remove terminal cloud files now</button>}
    </section>}
  </>
}
