import { useEffect, useState } from 'react'
import { bytesLabel } from './replayFiles'
import {timeLabel,type SubmittedMapType} from './logicalMaps'

export type SubmissionHandoff = { paths: string[]; opponent: string; mode: 'normal' | 'rehost'; submission: string; logical_map_id?:string; series_id?:string; match_date?:string }
type API = <T>(path: string, method?: string, body?: unknown) => Promise<T>
type Folder = { first_file_modified_at?:string|null; last_file_modified_at?:string|null; files?:number; bytes?:number; id: string; name: string; disposition: string | null; path?: string; map?: string; rounds?: number; match_type?: string; score?: number[]; our_score?: number|null; their_score?: number|null; tracked_count?: number; eligible?: boolean; rehost_eligible?: boolean; duplicate?: boolean; status?: string }
type LogicalMap={id:string;index:number;type:SubmittedMapType;segments:{index:number;folder_id:string}[]}
type Submission = {schema_version?:number;maps?:LogicalMap[];reviewed_maps?:LogicalMap[];local_receipts?:{folder_ids:string[];synced:boolean}[];series_context?:{series_id:string;team_slug:string;season_slug:string;opponent:string;match_date:string}|null; id: string; display_id: string; team_slug: string; team_name: string; season_slug: string; season_name: string; opponent: string; match_date: string; submitter: string; discord: string; rehost: string; notes: string; status: string; folders: Folder[]; files?:{folder_id:string;declared_size:number}[]; objects_deleted_at: number | null; actual_bytes: number; submitted_at: number | null }
type Storage = { configured: boolean; message?: string; enabled: boolean; stored_bytes: number; reserved_bytes: number; cap_bytes: number; pending_bytes: number; terminal_bytes: number; pending_count: number; percent: number; last_reconciled: number | null }

export function SubmissionsPage({ api, teams, seasons, handoff, changed }: { api: API; teams: { id: number; slug: string; name: string; active: number }[]; seasons: { slug: string; name: string; active: number }[]; handoff: (value: SubmissionHandoff, team: number, season: string) => void; changed: (count: number) => void }) {
  const [storage, setStorage] = useState<Storage | null>(null), [items, setItems] = useState<Submission[]>([]), [all, setAll] = useState(false)
  const [detail, setDetail] = useState<Submission | null>(null), [folders, setFolders] = useState<Folder[]>([]), [reviewed,setReviewed] = useState<LogicalMap[]>([]),[dirty,setDirty]=useState(false)
  const [team, setTeam] = useState(''), [season, setSeason] = useState('')
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false), [reason, setReason] = useState(''), [notes, setNotes] = useState('')
  async function load() { const [s, list] = await Promise.all([api<Storage>('/submissions/storage'), api<Submission[]>('/submissions?status=' + (all ? 'all' : 'pending'))]); setStorage(s); setItems(list); changed(s.pending_count || 0) }
  useEffect(() => { void load().catch(e => setError(e.message)) }, [all])
  async function action(work: () => Promise<void>) { setBusy(true); setError(''); setNotice(''); try { await work() } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  async function open(id: string) { const s = await api<Submission>('/submissions/' + id); setDetail(s); setFolders([]);setReviewed(s.reviewed_maps||[]);setDirty(false); setReason(''); setNotes(''); setTeam(String(teams.find(t => t.slug === (s.series_context?.team_slug||s.team_slug) && t.active)?.id || '')); setSeason(seasons.find(p => p.slug === (s.series_context?.season_slug||s.season_slug))?.slug || seasons.find(p => p.active)?.slug || '');  }
  async function inspect() { if (!detail) return; await api('/submissions/' + detail.id + '/stage', 'POST', {}); const result = await api<{ folders: Folder[] }>('/submissions/' + detail.id + '/inspect', 'POST', { team_id: Number(team), season_slug: season }); const refreshed=await api<Submission>('/submissions/'+detail.id);setDetail(refreshed);if(!dirty)setReviewed(refreshed.reviewed_maps||[]);setFolders(result.folders);await load() }
  const resolved=new Set([...(detail?.folders.filter(f=>f.disposition).map(f=>f.id)||[]),...(detail?.local_receipts?.flatMap(r=>r.folder_ids)||[])])
  function update(index:number,value:LogicalMap){setReviewed(reviewed.map((m,i)=>i===index?value:m));setDirty(true)}
  async function save(){if(!detail)return;const value=await api<{reviewed_maps:LogicalMap[]}>('/submissions/'+detail.id+'/structure','POST',{maps:reviewed});setReviewed(value.reviewed_maps);setDirty(false);setNotice('Reviewed structure saved locally. Original submitted structure preserved.');}
  async function reject(ids:string[]){if(!detail||!reason.trim())return;if(!window.confirm('Reject these remaining folders? Existing local imports stay valid.'))return;await api('/submissions/'+detail.id+'/reject','POST',{folder_ids:ids,reason,notes});await open(detail.id);await load()}
  function launch(map:LogicalMap){if(!detail)return;const selected=map.segments.map(part=>folders.find(f=>f.id===part.folder_id)!);const context=detail.series_context;const same=context?.team_slug===teams.find(t=>t.id===Number(team))?.slug&&context?.season_slug===season;handoff({paths:selected.map(f=>f.path!),opponent:same?context!.opponent:detail.opponent,mode:map.type as 'normal'|'rehost',submission:detail.display_id,logical_map_id:map.id,series_id:same?context!.series_id:undefined,match_date:same?context!.match_date:detail.match_date},Number(team),season)}

  return <><div className="admin-heading"><div><span className="eyebrow">PRIVATE REPLAY INBOX</span><h1>Submissions</h1><p>Review submitted folders locally before explicitly importing them as NECC.</p></div><button className="admin-button secondary" disabled={busy} onClick={() => void action(load)}>Refresh</button></div>
    {error && <div className="admin-inline-error" role="alert">{error}</div>}{notice && <div className="admin-notice success" role="status">{notice}</div>}
    {storage?.configured ? <section className="admin-panel"><h2>Cloud storage · {storage.percent.toFixed(1)}%</h2><p>Stored {bytesLabel(storage.stored_bytes)} · Reserved {bytesLabel(storage.reserved_bytes)} · Cap {bytesLabel(storage.cap_bytes)}</p><p>Pending {bytesLabel(storage.pending_bytes)} · Imported/rejected {bytesLabel(storage.terminal_bytes)} · {storage.pending_count} awaiting review</p>{storage.percent >= 75 && <p className="negative">Storage warning: {storage.percent >= 100 ? '100%' : storage.percent >= 95 ? '95%' : storage.percent >= 85 ? '85%' : '75%'} threshold reached. Intake stops at the cap.</p>}<p>Last reconciliation: {storage.last_reconciled ? new Date(storage.last_reconciled * 1000).toLocaleString() : 'Not yet run'}. Terminal files are retained seven days; pending files never expire.</p><div className="admin-actions">
      <button className="admin-button secondary" disabled={busy} onClick={() => void action(async () => { let result: { complete: boolean }; do { result = await api('/submissions/reconcile', 'POST', {}) } while (!result.complete); await load(); setNotice('Actual R2 storage reconciled.') })}>Reconcile storage</button>
      <button className="admin-button secondary" disabled={busy} onClick={() => void action(async () => { await api('/submissions/cleanup', 'POST', {}); await load(); setNotice('Expired upload sessions and eligible terminal files cleaned.') })}>Run retention cleanup</button>
      <button className="admin-button secondary" disabled={busy} onClick={() => void action(async () => { await api('/submissions/options', 'POST', {}); setNotice('Public team and active season choices synchronized.') })}>Sync team/season choices</button>
      <button className="admin-button" disabled={busy} onClick={() => void action(async () => { await api('/submissions/settings', 'POST', { enabled: !storage.enabled }); await load() })}>{storage.enabled ? 'Disable public submissions' : 'Enable public submissions'}</button>
    </div></section> : <div className="admin-empty">{storage?.message || 'Loading private inbox…'}</div>}
    <label><input type="checkbox" checked={all} onChange={e => setAll(e.target.checked)} disabled={busy}/> Include reviewed submissions</label>
    <section className="admin-panel"><h2>Replay submissions</h2>{!items.length && <p>No submissions in this view.</p>}{items.map(s => <div className="activity-row" key={s.id}><span><b>{s.display_id} · {s.team_name} vs {s.opponent}</b><small>{s.season_name} · {s.match_date} · {s.submitter} · {s.folders.length} folders · {bytesLabel(s.actual_bytes)} · {s.schema_version===2?`${s.maps?.length||0} logical maps`:`Legacy / rehost: ${s.rehost}`} · {s.discord&&'Discord: '+s.discord+' · '}{s.submitted_at&&new Date(s.submitted_at*1000).toLocaleString()} · {s.status}</small></span><button className="admin-button secondary" disabled={busy} onClick={() => void action(() => open(s.id))}>Review</button></div>)}</section>
    {detail && <section className="admin-panel"><h2>{detail.display_id} · {detail.status}</h2><p><b>Submitted as:</b> {detail.team_name} · {detail.season_name} · vs {detail.opponent} · {detail.match_date}</p><p>Submitted by {detail.submitter}{detail.discord && ' · Discord: ' + detail.discord}. {detail.schema_version===2?`${detail.maps?.length||0} submitted logical maps`:`Legacy submission / rehost: ${detail.rehost}`}</p><p>{detail.folders.length} replay folders · {bytesLabel(detail.actual_bytes)}</p><p>Private submitter notes: {detail.notes || 'None'}</p>
      {['pending', 'reviewing'].includes(detail.status) && <><div className="admin-form-grid"><label>Importing as team<select value={team} onChange={e => { setTeam(e.target.value); setFolders([]) }}><option value="">Choose a team</option>{teams.filter(t => t.active).map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Importing into season<select value={season} onChange={e => { setSeason(e.target.value); setFolders([]) }}><option value="">Choose a season</option>{seasons.map(s => <option key={s.slug} value={s.slug}>{s.name}</option>)}</select></label></div>
        <button className="admin-button" disabled={busy || !team || !season} onClick={() => void action(inspect)}>Download, verify & inspect locally</button>
        <p>Inspection uses the existing trusted local parser. Uploading or downloading does not import statistics.</p>
        <p>Submitted organization is a hint. Save any corrections below before opening the trusted normal/rehost importer. File times are identification hints only.</p>
        {detail.maps?.length? <details><summary>Original submitted structure</summary>{detail.maps.map(map=><p key={map.id}>Map {map.index} / {map.type}: {map.segments.map(part=>detail.folders.find(f=>f.id===part.folder_id)?.name).join(' / ')}</p>)}</details>:<p>Legacy flat submission: classify and group its folders locally.</p>}
        <div className="submission-map-list">{reviewed.map((map,i)=>{
          const frozen=map.segments.some(p=>resolved.has(p.folder_id)),ready=map.segments.every(part=>{const f=folders.find(f=>f.id===part.folder_id);return f?.path&&!resolved.has(part.folder_id)&&!f.duplicate&&(map.type==='normal'?f.eligible:f.rehost_eligible)})
          return <section className="submission-map-card" key={map.id}><h3>Map {map.index} / {map.type==='normal'?'Normal':map.type==='rehost'?'Rehosted':'Not sure'}</h3><label>Reviewed Map {map.index} type<select disabled={busy||frozen} value={map.type} onChange={e=>{const type=e.target.value as SubmittedMapType;if(type==='normal'&&map.segments.length>1){setError('Move the extra folders to another reviewed map before changing to Normal. No selections were removed.');return;}update(i,{...map,type,segments:type==='rehost'&&map.segments.length===1?[...map.segments,{index:2,folder_id:''}]:map.segments})}}><option value="normal">Normal</option><option value="rehost">Rehosted</option><option value="unsure">Not sure / classify before import</option></select></label>
            {map.segments.map((part,j)=>{const original=detail.folders.find(f=>f.id===part.folder_id),f=folders.find(f=>f.id===part.folder_id)||original;return <div className="submission-part" key={j}><label>Map {map.index} / Part {j+1}<select disabled={busy||frozen} value={part.folder_id} onChange={e=>update(i,{...map,segments:map.segments.map((p,k)=>k===j?{...p,folder_id:e.target.value}:p)})}><option value="">Choose folder</option>{detail.folders.map(folder=><option key={folder.id} value={folder.id} disabled={folder.id!==part.folder_id&&reviewed.some(m=>m.segments.some(p=>p.folder_id===folder.id))}>{folder.name}</option>)}</select></label>
              {f&&<><b>{f.name}</b><small>{timeLabel(f.first_file_modified_at,f.last_file_modified_at)} / {f.files??detail.files?.filter(file=>file.folder_id===f.id).length??'?'} replay files / {bytesLabel(f.bytes??detail.files?.filter(file=>file.folder_id===f.id).reduce((n,file)=>n+file.declared_size,0)??0)}</small><p>{f.map||'Not inspected'} / {f.match_type||'Unknown match type'} / {f.rounds??'?'} rounds / {f.tracked_count??'?'} roster matches{f.disposition&&` / ${f.disposition}`}{f.status&&` / ${f.status}`}</p>{!resolved.has(f.id)&&<button className="admin-button secondary" disabled={busy||dirty||!reason.trim()} onClick={()=>void action(()=>reject([f.id]))}>Reject this remaining folder</button>}</>}
              {!frozen&&map.type!=='normal'&&<div className="detail-actions"><button className="admin-button secondary" disabled={busy||j===0} aria-label={`Move reviewed Map ${map.index} Part ${j+1} up`} onClick={()=>{const parts=[...map.segments];[parts[j-1],parts[j]]=[parts[j],parts[j-1]];update(i,{...map,segments:parts.map((p,k)=>({...p,index:k+1}))})}}>Move up</button><button className="admin-button secondary" disabled={busy||j===map.segments.length-1} aria-label={`Move reviewed Map ${map.index} Part ${j+1} down`} onClick={()=>{const parts=[...map.segments];[parts[j+1],parts[j]]=[parts[j],parts[j+1]];update(i,{...map,segments:parts.map((p,k)=>({...p,index:k+1}))})}}>Move down</button><button className="admin-button secondary" disabled={busy||map.segments.length<=1} onClick={()=>{if(part.folder_id&&!window.confirm('Remove this part slot? Reassign its folder before saving.'))return;update(i,{...map,segments:map.segments.filter((_,k)=>k!==j).map((p,k)=>({...p,index:k+1}))})}}>Remove part</button></div>}
            </div>})}
            {!frozen&&map.type!=='normal'&&<button className="admin-button secondary" disabled={busy||reviewed.reduce((n,m)=>n+m.segments.length,0)>=12} onClick={()=>update(i,{...map,segments:[...map.segments,{index:map.segments.length+1,folder_id:''}]})}>Add part</button>}
            <div className="detail-actions"><button className="admin-button" disabled={busy||dirty||map.type==='unsure'||!ready} onClick={()=>launch(map)}>{map.type==='rehost'?'Open Rehost Builder':'Open Normal Import'}</button><button className="admin-button secondary" disabled={busy||dirty||!reason.trim()||!map.segments.some(p=>p.folder_id&&!resolved.has(p.folder_id))} onClick={()=>void action(()=>reject(map.segments.filter(p=>!resolved.has(p.folder_id)).map(p=>p.folder_id)))}>Reject remaining Map {map.index} folders</button>{!frozen&&<button className="admin-button secondary" disabled={busy||reviewed.length<=1} onClick={()=>{if(!window.confirm('Remove this map card? Reassign its folders before saving.'))return;setReviewed(reviewed.filter((_,k)=>k!==i).map((m,k)=>({...m,index:k+1})));setDirty(true)}}>Remove map card</button>}</div>
          </section>
        })}</div>
        <div className="detail-actions"><button className="admin-button secondary" disabled={busy||!folders.length||reviewed.length>=12} onClick={()=>{setReviewed([...reviewed,{id:crypto.randomUUID(),index:reviewed.length+1,type:'normal',segments:[{index:1,folder_id:''}]}]);setDirty(true)}}>Add reviewed map</button><button className="admin-button" disabled={busy||!folders.length||!dirty} onClick={()=>void action(save)}>Save reviewed map structure</button></div>{dirty&&<p className="admin-inline-error">Save reviewed structure before import. Every folder must remain assigned exactly once.</p>}
        <label>Rejection reason<input value={reason} maxLength={240} onChange={e => setReason(e.target.value)}/></label><label>Private admin notes<textarea value={notes} maxLength={2000} onChange={e => setNotes(e.target.value)}/></label><button className="admin-button secondary" disabled={busy || !reason.trim()} onClick={() => { if (window.confirm('Reject all remaining unconsumed folders? Existing local imports remain intact.')) void action(async () => { await api('/submissions/' + detail.id + '/reject', 'POST', { reason, notes }); await open(detail.id); await load() }) }}>Reject remaining folders</button>
      </>}
      <button className="admin-button secondary" disabled={busy} onClick={() => void action(async () => { await api('/submissions/' + detail.id + '/sync', 'POST', {}); await open(detail.id); await load(); setNotice('Local archive receipts synchronized.') })}>Retry cloud status sync</button>
      {['imported', 'rejected', 'failed'].includes(detail.status) && !detail.objects_deleted_at && <button className="admin-button secondary" disabled={busy} onClick={() => { const confirmation = window.prompt('Delete terminal cloud copies now? Local archived replays are preserved. Type ' + detail.display_id); if (confirmation === detail.display_id) void action(async () => { await api('/submissions/' + detail.id + '/purge', 'POST', { confirm_display_id: confirmation }); await open(detail.id); await load() }) }}>Remove terminal cloud files now</button>}
    </section>}
  </>
}
