import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { HashRouter, Link, NavLink, Route, Routes, useParams } from 'react-router-dom'
import { ArrowUpRight, Crosshair, Swords, Trophy, CalendarDays, Info } from 'lucide-react'
import './style.css'
import { RatingFormula } from './ratingFormula'

type Stats = {slug:string;name:string;rating:number|null;rounds:number;maps:number;kills:number;deaths:number;kd:number|null;kd_diff:number;kpr:number;kost:number;srv:number;hs:number;opening_kills:number;opening_deaths:number;entry_diff:number;plants:number;disables:number;clutches:number;clutch_1v1:number;clutch_1v2:number;clutch_1v3:number;clutch_1v4:number;clutch_1v5:number;refrag_kills:number;deaths_traded:number;kills_traded:number;untraded_kills:number;untraded_deaths:number;pivot_kills:number;pivot_deaths:number;teamkills:number;operators:Record<string,Record<string,number>>;sides:Record<string,{rounds:number;kills:number;deaths:number;kd:number|null;kpr:number}>}
type Match = {id:string;series_id:string;season:string;opponent:string;date:string;week:string;notes:string;map:string;our_score:number;their_score:number;result:string;demo:boolean;rating?:number|null}
type Season = {slug:string;name:string;demo:boolean;maps:number;wins:number;rounds_won:number;rounds:number;players:Stats[];matches:Match[]}
type Index = {team:{name:string;short_name:string;accent:string};active_season:string|null;seasons:{slug:string;name:string}[];players:{slug:string;name:string}[]}
const base = import.meta.env.BASE_URL + 'data/'
function useData<T>(path:string) { const [data,setData]=useState<T|null>(null); const [error,setError]=useState(''); useEffect(()=>{setData(null);setError('');fetch(base+path).then(r=>{if(!r.ok)throw Error(`Data unavailable (${r.status})`);return r.json()}).then(setData).catch(e=>setError(e.message))},[path]);return {data,error} }
const pct=(n:number)=>`${Math.round(n*100)}%`
const dec=(n:number|null,d=2)=>n===null?'—':n.toFixed(d)
const signed=(n:number)=>`${n>=0?'+':''}${n}`
const kd=(s:Stats)=>`${s.kills}-${s.deaths} (${signed(s.kd_diff)})`
const entry=(s:Stats)=>`${s.opening_kills}-${s.opening_deaths} (${signed(s.entry_diff)})`
const color=(n:number)=>n>0?'positive':n<0?'negative':''
const hints:Record<string,string>={Rating:'Collegiate composite performance rating',KOST:'Rounds with a kill, objective, survival or traded death',Entry:'Opening kills minus opening deaths',KPR:'Enemy kills per round',SRV:'Rounds survived divided by rounds played','HS%':'Headshot kills divided by enemy kills','1vX':'Rounds won after becoming the last player alive against one or more opponents.'}
function Loading({error}:{error:string}){return <div className="empty">{error||'Loading statistics…'}</div>}
function App(){const {data:index,error}=useData<Index>('index.json');const [season,setSeason]=useState(localStorage.getItem('necc-season')||'');useEffect(()=>{if(index&&!season)setSeason(index.active_season||index.seasons[0]?.slug||'')},[index,season]);useEffect(()=>{if(season)localStorage.setItem('necc-season',season)},[season]);if(!index)return <Loading error={error}/>;return <div className="app" style={{'--accent':index.team.accent} as React.CSSProperties}><header className="topbar"><div className="brand"><span className="brand-mark"><Crosshair size={22}/></span><div><b>{index.team.short_name}</b><small>NECC / SIEGE INTELLIGENCE</small></div></div><nav><NavLink to="/">Overview</NavLink><NavLink to="/players">Players</NavLink><NavLink to="/matches">Matches</NavLink><NavLink to="/methodology">Methodology</NavLink></nav><label className="season-select">SEASON <select value={season} onChange={e=>setSeason(e.target.value)}>{index.seasons.map(s=><option key={s.slug} value={s.slug}>{s.name}</option>)}</select></label></header><main><Routes><Route path="/" element={<Overview season={season} team={index.team.name}/>}/><Route path="/players" element={<Players season={season}/>}/><Route path="/players/:slug" element={<PlayerPage season={season}/>}/><Route path="/matches" element={<Matches season={season}/>}/><Route path="/matches/:id" element={<MapPage/>}/><Route path="/methodology" element={<Methodology/>}/></Routes></main><footer><span>{index.team.name} · NECC statistics</span><span>Built from local match replays</span></footer></div>}
function Heading({eyebrow,title,subtitle}:{eyebrow:string;title:string;subtitle:string}){return <div className="heading"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></div>}
function StatCard({label,value,icon}:{label:string;value:string|number;icon?:React.ReactNode}){return <div className="statcard"><span>{label}{icon}</span><strong>{value}</strong></div>}
function Board({players}:{players:Stats[]}){const [sort,setSort]=useState<keyof Stats>('rating');const [desc,setDesc]=useState(true);const cols:[keyof Stats,string,(s:Stats)=>string][]=[['rating','Rating',s=>dec(s.rating)],['kost','KOST',s=>pct(s.kost)],['kd_diff','K-D',kd],['entry_diff','Entry',entry],['kpr','KPR',s=>dec(s.kpr)],['srv','SRV',s=>pct(s.srv)],['hs','HS%',s=>pct(s.hs)],['plants','Plants',s=>String(s.plants)],['clutches','1vX',s=>String(s.clutches)],['rounds','Rounds',s=>String(s.rounds)]];const sorted=[...players].sort((a,b)=>{const av=a[sort],bv=b[sort];return (Number(av??-Infinity)-Number(bv??-Infinity))*(desc?-1:1)});return <div className="table-wrap"><table><thead><tr><th>Player</th>{cols.map(([key,label])=><th key={key} onClick={()=>{setDesc(sort===key?!desc:true);setSort(key)}} title={hints[label]||`Sort by ${label}`}>{label} {sort===key?(desc?'↓':'↑'):''}</th>)}</tr></thead><tbody>{sorted.map((p,i)=><tr key={p.slug}><td><Link className="player-link" to={`/players/${p.slug}`}><span className="rank">{String(i+1).padStart(2,'0')}</span>{p.name}<ArrowUpRight size={14}/></Link></td>{cols.map(([key,,render])=><td key={key} className={key==='kd_diff'?color(p.kd_diff):key==='entry_diff'?color(p.entry_diff):key==='rating'?'rating':''}>{render(p)}</td>)}</tr>)}</tbody></table>{!players.length&&<div className="empty">No maps imported for this season yet.</div>}</div>}
function Overview({season,team}:{season:string;team:string}){const {data,error}=useData<Season>(`seasons/${season}.json`);if(!data)return <Loading error={error}/>;return <><Heading eyebrow="COMPETITIVE INTELLIGENCE / NECC" title={data.name.toUpperCase()} subtitle={`${team} performance across every imported NECC map.`}/>{data.demo&&<div className="demo">DEMO DATA · Synthetic matches for preview only</div>}<div className="cardgrid"><StatCard label="MAP RECORD" value={`${data.wins}–${data.maps-data.wins}`} icon={<Trophy size={16}/>}/><StatCard label="MAPS PLAYED" value={data.maps} icon={<Swords size={16}/>}/><StatCard label="ROUNDS WON" value={data.rounds_won} icon={<Crosshair size={16}/>}/><StatCard label="ROUND WIN RATE" value={pct(data.rounds?data.rounds_won/data.rounds:0)} icon={<CalendarDays size={16}/>}/></div><div className="section-title"><div><span className="eyebrow">THE ROSTER</span><h2>Player leaderboard</h2></div><span className="section-aside">Sorted by Rating</span></div><Board players={data.players}/><div className="section-title"><div><span className="eyebrow">LATEST ACTION</span><h2>Recent maps</h2></div><Link to="/matches">View all <ArrowUpRight size={15}/></Link></div><div className="match-grid">{data.matches.slice(0,3).map(m=><MatchCard key={m.id} m={m}/>)}</div></>}
function Players({season}:{season:string}){const {data,error}=useData<Season>(`seasons/${season}.json`);if(!data)return <Loading error={error}/>;return <><Heading eyebrow="NECC / ROSTER" title="PLAYERS" subtitle="Every teammate, one scoreboard. Select a player for round level detail."/><Board players={data.players}/></>}
function MatchCard({m}:{m:Match}){return <Link className="match-card" to={`/matches/${m.id}`}><div><span className="eyebrow">{m.date}</span><span className={`badge ${m.result.toLowerCase()}`}>{m.result}</span></div><h3>vs {m.opponent}</h3><div className="match-bottom"><span>{m.map}{m.rating!=null?` · Rating ${dec(m.rating)}`:''}</span><strong>{m.our_score} <em>:</em> {m.their_score}</strong></div></Link>}
function Matches({season}:{season:string}){const {data,error}=useData<Season>(`seasons/${season}.json`);if(!data)return <Loading error={error}/>;const groups:Record<string,Match[]>={};for(const m of data.matches)(groups[m.series_id]??=[]).push(m);return <><Heading eyebrow="NECC / MATCH HISTORY" title="MATCHES" subtitle="Every imported map, grouped by matchup."/>{data.demo&&<div className="demo">DEMO DATA · Synthetic matches</div>}{Object.entries(groups).map(([id,maps])=><section key={id}><div className="section-title"><div><span className="eyebrow">{maps[0].date} {maps[0].week?`/ WEEK ${maps[0].week}`:''}</span><h2>vs {maps[0].opponent}</h2></div><span className="section-aside">{maps.length} {maps.length===1?'map':'maps'}</span></div><div className="match-list">{maps.map(m=><MatchCard key={m.id} m={m}/>)}</div></section>)}{!data.matches.length&&<div className="empty">No NECC maps imported yet.</div>}</>}
function DetailGrid({s}:{s:Stats}){const rows:[string,string|number][]=[['Rounds',s.rounds],['Kills',s.kills],['Deaths',s.deaths],['KD',s.kd===null?'—':dec(s.kd)],['Opening kills',s.opening_kills],['Opening deaths',s.opening_deaths],['Refrag kills',s.refrag_kills],['Deaths traded',s.deaths_traded],['Kills traded',s.kills_traded],['Untraded kills',s.untraded_kills],['Untraded deaths',s.untraded_deaths],['Pivot kills',s.pivot_kills],['Pivot deaths',s.pivot_deaths],['1vX Clutches',s.clutches],['1v1',s.clutch_1v1],['1v2',s.clutch_1v2],['1v3',s.clutch_1v3],['1v4',s.clutch_1v4],['1v5',s.clutch_1v5],['Plants',s.plants],['Disables',s.disables],['Teamkills',s.teamkills]];return <div className="detail-grid">{rows.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>}
function PlayerPage({season}:{season:string}){const {slug}=useParams();const [view,setView]=useState(season);useEffect(()=>setView(season),[season]);const {data,error}=useData<Stats&{matches:Match[]}>(`players/${slug}/${view}.json`);if(!data)return <Loading error={error}/>;return <><div className="profile-head"><Heading eyebrow="NECC / PLAYER PROFILE" title={data.name.toUpperCase()} subtitle={`${data.rounds} rounds across ${data.maps} maps`}/><button className="button" onClick={()=>setView(view==='career'?season:'career')}>{view==='career'?'View season':'View career'}</button></div><div className="cardgrid profile-cards"><StatCard label="RATING" value={dec(data.rating)}/><StatCard label="KOST" value={pct(data.kost)}/><StatCard label="K-D" value={kd(data)}/><StatCard label="ENTRY" value={entry(data)}/><StatCard label="KPR" value={dec(data.kpr)}/><StatCard label="SURVIVAL" value={pct(data.srv)}/><StatCard label="HEADSHOTS" value={pct(data.hs)}/></div><div className="two-col"><section className="panel"><span className="eyebrow">COMPLETE BREAKDOWN</span><h2>Performance</h2><DetailGrid s={data}/></section><section className="panel"><span className="eyebrow">ROUND CONTEXT</span><h2>Attack / Defense</h2><div className="sides">{['Attack','Defense'].map(side=><div key={side}><h3>{side}</h3><p>{data.sides[side].rounds} rounds</p><strong>{data.sides[side].kills}–{data.sides[side].deaths}</strong><span>KPR {dec(data.sides[side].kpr)} · KD {data.sides[side].kd===null?'—':dec(data.sides[side].kd)}</span></div>)}</div><span className="eyebrow operator-label">OPERATOR USAGE</span><div className="operators">{['Attack','Defense'].map(side=><div key={side}><h3>{side}</h3>{Object.entries(data.operators[side]||{}).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([op,n])=><div className="operator" key={op}><span>{op}</span><div><i style={{width:`${100*n/Math.max(1,...Object.values(data.operators[side]))}%`}}/></div><b>{n}</b></div>)}</div>)}</div></section></div><div className="section-title"><div><span className="eyebrow">GAME LOG</span><h2>Recent maps</h2></div></div><div className="match-list">{data.matches.map(m=><MatchCard key={m.id} m={m}/>)}</div></>}
function MapPage(){const {id}=useParams();const {data,error}=useData<Match&{players:Stats[];rounds:{number:number;side:string;result:string;site:string}[]}>(`matches/${id}.json`);if(!data)return <Loading error={error}/>;return <><Heading eyebrow={`NECC / ${data.season.toUpperCase()}`} title={`${data.our_score} : ${data.their_score}`} subtitle={`vs ${data.opponent} · ${data.map} · ${data.date}`}/>{data.demo&&<div className="demo">DEMO DATA · Synthetic match</div>}<div className="section-title"><div><span className="eyebrow">YOUR TEAM</span><h2>Map performance</h2></div><span className={`badge ${data.result.toLowerCase()}`}>{data.result}</span></div><Board players={data.players}/><div className="section-title"><div><span className="eyebrow">ROUND BY ROUND</span><h2>Breakdown</h2></div></div><div className="rounds">{data.rounds.map(r=><div className="round" key={r.number}><b>R{r.number}</b><span>{r.side}</span><span>{r.site}</span><strong className={r.result==='Win'?'positive':'negative'}>{r.result}</strong></div>)}</div></>}
function Methodology(){const {data,error}=useData<{trade_window_seconds:number;rating_version:string}>('methodology.json');if(!data)return <Loading error={error}/>;const terms=[['K-D','Enemy kills minus deaths; manually corrected final map totals appear here when available.'],['KD','Enemy kills divided by deaths; zero deaths displays as a dash.'],['KPR','Enemy kills divided by rounds played.'],['Entry','Opening enemy kills minus opening deaths. Teamkills are excluded.'],['KOST','Share of rounds with an enemy kill, plant or disable, survival, or a traded death.'],['SRV','Share of rounds survived.'],['HS%','Headshot enemy kills divided by enemy kills.'],['1vX clutches','Rounds won after becoming the last player alive against one to five opponents. The size is set when the player first becomes the sole survivor.'],['Objective plays','Defuser plants plus disables.'],['Refrag kills','Kills of an enemy who just killed a teammate within the trade window.'],['Deaths traded','Deaths where a teammate killed the original killer within the trade window.'],['Kills traded','Kills followed by the killer’s death to the victim’s teammate within the trade window.'],['Pivot kills','Kills when the killer’s team is tied or behind in alive players.'],['Operator usage','The operator selected when action phase begins. Rounds with unresolved operator data are excluded from operator counts.']];return <><Heading eyebrow="HOW THE NUMBERS WORK" title="METHODOLOGY" subtitle="Transparent definitions for every competitive stat on this site."/><div className="method-hero"><Info size={22}/><div><strong>{data.rating_version === "siege_style_v2" ? "Independent Siege-style model" : "Open collegiate model"}</strong><p>Rating version: {data.rating_version} · Trade window: {data.trade_window_seconds} seconds</p></div></div><div className="method-grid">{terms.map(([term,description])=><div className="method-card" key={term}><h3>{term}</h3><p>{description}</p></div>)}</div><RatingFormula version={data.rating_version}/></>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><HashRouter><App/></HashRouter></React.StrictMode>)
