import { useEffect, useState, type ReactNode } from 'react'
import { Link, useParams } from 'react-router-dom'
import { RatingFormula } from './ratingFormula'
import { RatingChart } from './ratingChart'
import './methodology.css'

const categories = ['Overview', 'Rating', 'Core Stats', 'Objectives', 'Advanced Stats'] as const
const slug = (label: string) => label.toLowerCase().replaceAll(' ', '-')

function Explanation({ title, summary, children }: { title: string; summary: string; children: ReactNode }) {
  return <details className="explanation"><summary><span><strong>{title}</strong><span>{summary}</span></span><span className="expand-mark" aria-hidden="true">+</span></summary><div className="explanation-body">{children}</div></details>
}

export function Methodology() {
  const params = useParams()
  const requested = params['*'] || 'overview'
  const current = categories.find(c => slug(c) === requested) || 'Overview'
  const [settings, setSettings] = useState<{ trade_window_seconds: number; rating_version: string } | null>(null)
  const [error, setError] = useState(false)
  useEffect(() => {
    const controller = new AbortController()
    fetch(import.meta.env.BASE_URL + 'data/methodology.json', { signal: controller.signal })
      .then(r => { if (!r.ok) throw Error('Unavailable'); return r.json() }).then(setSettings)
      .catch(e => { if (e.name !== 'AbortError') setError(true) })
    return () => controller.abort()
  }, [])
  const window = settings?.trade_window_seconds
  return <div className="methodology-page">
    <div className="heading"><span className="eyebrow">HOW THE NUMBERS WORK</span><h1>Methodology</h1><p>A quick guide to player performance, with the details there when you want them.</p></div>
    <nav className="method-nav" aria-label="Methodology sections">{categories.map(c => <Link key={c} to={`/methodology/${slug(c)}`} aria-current={current === c ? 'page' : undefined}>{c}</Link>)}</nav>
    <section className="method-section" aria-labelledby={`method-${slug(current)}`} key={current}>
      <div className="method-section-title"><span className="eyebrow">{String(categories.indexOf(current)+1).padStart(2, '0')} / THE GUIDE</span><h2 id={`method-${slug(current)}`}>{current}</h2></div>
      {current === 'Overview' && <>
        <div className="method-intro panel"><h3>Every number starts with a round.</h3><p>Statistics are reconstructed from Rainbow Six Siege match replays. UAH’s confirmed NECC matches are organized by team and season, so you can follow a single map or a player’s full career.</p><p>Rating is a performance estimate. KOST describes round involvement. The rest of the breakdown adds context: eliminations, objectives, openings, trades and clutches.</p><Link className="button" to="/methodology/rating">Explore Rating →</Link></div>
        <div className="scope-guide"><div className="panel"><span className="eyebrow">ON A TEAM PAGE</span><h3>That team’s history</h3><p><strong>Season</strong> shows the selected team’s maps in that season. <strong>Career</strong> combines regular roster appearances for that team across seasons. The separate Subs view includes only actual substitute appearances for the selected team.</p></div><div className="panel"><span className="eyebrow">ON A PLAYER PROFILE</span><h3>The player’s whole story</h3><p><strong>Season</strong> includes the player’s selected-season performance across UAH teams. <strong>Career</strong> includes their regular roster history across UAH teams. Substitute Stats stay separate; substitute appearances never enter normal Career totals or Rating trends.</p></div></div>
        <Explanation title="Coverage & player history" summary="What an empty view or missing Rating means."><p>A new team or season can have a roster before any matches are recorded. Alumni are hidden from Player Stats by default; Include Alumni brings them back. Their profiles and historical matches remain available.</p><p>A dash for Rating means there are no eligible Rating inputs in that view. Player profiles show eligible rounds and maps separately from the full performance record. Removing a public table column never removes the underlying statistic.</p></Explanation>
      </>}
      {current === 'Rating' && <>
        <div className="method-intro panel"><span className="version-label">CURRENT MODEL · siege_style_v3</span><h3>One number. Several ways to contribute.</h3><p>Rating combines elimination output, round involvement, survival, openings, trades, clutches and objectives into a single performance estimate.</p><p>It is independently modeled to approximate modern SiegeGG-style player Rating. It is <strong>not SiegeGG’s proprietary official formula</strong>, and it is not an official Ubisoft score.</p></div>
        <div className="scope-guide"><Explanation title="What feeds Rating?" summary="Nine feature families, drawn from eligible rounds."><ul><li>Credited kills per round and teamkill rate</li><li>Extra kills in multikill rounds</li><li>Opening kill minus opening death rate</li><li>Successful clutches, weighted by their initial size</li><li>KOST and survival</li><li>Traded-death minus traded-kill rate</li><li>Completed plants and disables</li></ul><p>There is no operator-specific bonus. All counts are converted to rates per eligible round.</p></Explanation><Explanation title="Maps, series, seasons & careers" summary="Aggregate the inputs first; calculate Rating once."><p>A map uses its eligible rounds. Series, season and career views sum the eligible inputs within that view, then apply the same frozen formula. They do not take an unweighted average of map Ratings.</p><p>Team views include only that team’s maps. A global player profile can span teams. A player’s history and their Rating coverage can therefore have different totals.</p></Explanation></div>
        <Explanation title="Series Rating" summary="The same frozen model, across the recorded maps you played."><p>Series Rating combines trusted v3 counts from eligible maps within one matchup, then evaluates the existing formula once over those eligible rounds. It does not average rounded map Ratings or introduce a new model.</p><p>Because this model is affine in additive per-round features, this equals a round-weighted mean of full-precision eligible map Ratings. Aggregate inputs remain authoritative.</p><p>Coverage is player-specific: rated maps and rounds are shown against the recorded maps and rounds that player actually played. Ineligible maps still contribute to displayed performance. No eligible rounds means a dash, never a fabricated zero.</p><p>Player Rating trends show one Series Rating per matchup, with opponent, date and coverage on hover, focus or tap. Recorded-map scores describe imported maps, not proof of a complete series result. This remains an independent estimate, not an official SiegeGG formula.</p></Explanation>
        <Explanation title="Rating eligibility" summary="Whole maps must have complete, trustworthy inputs."><p>v3 requires complete Ubisoft credited-kill counts, verified plants/disables and verified event order for openings and clutches. Maps with incomplete replay data or manual final K/D corrections do not qualify.</p><p>Eligibility is decided for an entire map. A map that does not qualify still contributes to the displayed historical performance statistics. Missing evidence is never treated as zero, and partially supported maps are not mixed into Rating.</p></Explanation>
        <RatingChart/>
        <Explanation title="Technical details" summary="Frozen equation, input definitions and validation.">
          <RatingFormula version="siege_style_v3"/>
          <h4>Exact feature definitions</h4><p>Extra multikills sum max(credited kills − 1, 0) for each round. Native opening differential uses the first opposing final elimination in verified replay event order. Successful clutch sizes contribute X(X+1)/2: 1, 3, 6, 10 or 15.</p><p>Trade differential is deaths traded minus kills traded. Trade differential and KOST’s traded-death flag retain the frozen 8-second legacy policy. Objectives are verified completed plants plus disables. Displayed Entry, trades and 1vX retain their historical event chronology; Rating independently validates native opening/clutch order.</p><h4>Immutable versions</h4><p>The equation above is rounded for readability. Production uses full-precision standardized coefficients, training means and scales. Each version’s coefficients and input policy are frozen; historical v2 input snapshots remain preserved.</p><h4>Final validation</h4><p>The model was frozen before accessing APAC North Stage 1 2026 target Ratings. The final test used 110 clean player-map observations from 11 maps and eight rosters. v3 and the exact original v2 were evaluated on the same rows, with the existing quality and acceptance gates unchanged. This event was evaluated once, with no refitting afterward.</p><a className="method-source" href="https://github.com/uah-r6/uah-r6.github.io/blob/main/r6stats/stats/rating_v3.py">Full-precision production coefficients ↗</a>
        </Explanation>
        <Explanation title="Rating history" summary="Three preserved versions; v3 is the current model."><dl className="history-list"><div><dt>collegiate_v1</dt><dd>Early collegiate calibration.</dd></div><div><dt>siege_style_v2</dt><dd>First professionally validated SiegeGG-style model.</dd></div><div><dt>siege_style_v3</dt><dd>Current model: validated credited counts, verified objectives and native event order.</dd></div></dl></Explanation>
      </>}
      {current === 'Core Stats' && <>
        <div className="method-intro panel"><h3>KOST: did you contribute to the round?</h3><p>A round counts when <strong>at least one</strong> of Kill, Objective, Survive or Trade is satisfied. Doing several still counts as one KOST round. The percentage is qualifying rounds divided by rounds played.</p></div>
        <div className="kost-grid">
          <Explanation title="K · Kill" summary="Earn an enemy kill."><p>A credited enemy kill qualifies on supported maps. Unsupported whole maps use final-elimination counts. Teamkills do not qualify.</p></Explanation>
          <Explanation title="O · Objective" summary="Complete a plant or disable."><p>A recorded defuser plant or disable qualifies. Starting an interaction without completing it does not.</p></Explanation>
          <Explanation title="S · Survive" summary="Stay alive through the round."><p>Surviving qualifies even if your team loses. You do not need a kill or objective as well.</p></Explanation>
          <Explanation title="T · Trade" summary="Have your death traded."><p>A teammate eliminates your original killer within the trade window. This is a traded death, not simply earning a refrag kill yourself.</p></Explanation>
        </div>
        <div className="definitions-grid">
          <Explanation title="Kills" summary="Enemy eliminations credited to a player."><p>Siege can credit the kill to the player who downed an opponent even when another player performs the final elimination. On supported maps, this site follows Ubisoft’s credited kill for statistical kill totals.</p><p>Teamkills and suicides are excluded from enemy kills.</p></Explanation>
          <Explanation title="Deaths" summary="Times the player was eliminated."><p>Deaths include enemy eliminations, teamkills and suicides. A player can die only once in a round.</p></Explanation>
          <Explanation title="K/D & K-D" summary="Kill ratio and kill differential."><p>K/D is enemy kills divided by deaths; zero deaths displays as a dash. K-D shows kills, deaths and their difference, such as 20–15 (+5).</p></Explanation>
          <Explanation title="KPR" summary="Enemy kills per round played."><p>Enemy kills divided by rounds played. Season and career values use the combined kill and round counts.</p></Explanation>
          <Explanation title="Survival · SRV" summary="The share of rounds finished alive."><p>Rounds survived divided by rounds played. A survived loss still counts toward survival.</p></Explanation>
          <Explanation title="Headshots · HS%" summary="Headshot final eliminations as a percentage."><p>Headshot final eliminations divided by all enemy final eliminations, or zero when there are none. This describes the finishing elimination, not the original downer’s shot.</p></Explanation>
          <Explanation title="Multikills" summary="Rounds with two or more enemy kills."><p>Each round is grouped by its kill total: 2K, 3K, 4K or 5K. On supported maps these use credited kills. Rating’s extra-kill term counts kills beyond the first in each round.</p></Explanation>
          <Explanation title="Technical details · kill attribution" summary="Count statistics and event statistics have distinct evidence."><p>Complete validated maps use stable Ubisoft round counters for kills, K/D, KPR, side kills, multikills and KOST Kill. Unsupported maps retain historical final-elimination counts for the whole map; there is no partial-map mixing.</p><p>Opening, trade, pivot, untraded and headshot statistics follow final-elimination events. A credited downer and the finisher can differ. Precise credited-owner opening and trade attribution is not currently supported.</p></Explanation>
        </div>
      </>}
      {current === 'Objectives' && <>
        <div className="method-intro panel"><h3>Finishing the action matters.</h3><p>Plants and disables count completed defuser interactions. Where supported, replay interaction evidence identifies the player who finishes the action.</p></div>
        <div className="definitions-grid"><Explanation title="Plants" summary="Completed attacker defuser plants."><p>The attacker who completes the plant receives one plant. A canceled attempt does not count.</p></Explanation><Explanation title="Disables" summary="Completed defender defuser disables."><p>The defender who completes the disable receives one disable. Disables remain in detailed performance statistics, KOST and eligible Rating inputs even though they are not a main Player Stats column.</p></Explanation><Explanation title="Objective plays" summary="Plants plus disables."><p>Objective plays combine both completed actions. A valid objective also satisfies the Objective condition in KOST.</p></Explanation><Explanation title="Technical details" summary="Completion evidence, actor safeguards and coverage."><p>Supported corrections require the replay’s core interaction occurrence and a verified player/team association. A timer owner or a nearby packet alone is not enough to assign the actor. Failed or ambiguous interactions are not guessed.</p><p>Historical objective data is preserved for display when complete verification is unavailable. v3 requires complete verified objective evidence for the whole map, including opponents; otherwise that map is excluded from Rating.</p></Explanation></div>
      </>}
      {current === 'Advanced Stats' && <><div className="method-intro panel"><h3>Selected round highlights</h3><p>Breakdown shows a few replay-verified UAH moments: 3K, 4K, ACE, successful clutches and completed objectives. Credited enemy counts determine multikills; verified native order determines clutches; corrected core evidence identifies objective actors.</p><p>Most rounds have no label. Related moments combine by player, with at most two compact groups. Opening kills, routine 2Ks, trades and event logs are intentionally omitted. Unsupported evidence is left unlabelled. A multikill can be notable even in a lost round.</p></div>
        <div className="method-intro panel"><h3>Who changes the round?</h3><p>Openings, trades and clutches describe the situations behind the totals. These statistics follow elimination events rather than assigning every event to the credited downer.</p></div>
        <div className="definitions-grid">
          <Explanation title="Opening kills / deaths & Entry" summary="The first opposing elimination of a round."><p>The finisher gets the opening kill and the victim gets the opening death. Entry is opening kills minus opening deaths. Teamkills and suicides are excluded from openings.</p></Explanation>
          <Explanation title="Trades & refrags" summary="A teammate answers an elimination quickly."><p>A refrag kill eliminates the enemy who just killed a teammate within the trade window. The teammate’s death is traded; the original killer’s kill is traded when the victim’s teammate eliminates them within that window.</p><p>{window !== undefined ? `The displayed trade window is ${window} seconds.` : error ? 'Trade-window settings are unavailable. The v3 Rating policy remains frozen at 8 seconds.' : 'Loading trade-window settings…'} v3 Rating retains its frozen 8-second trade policy.</p><p>A traded death qualifies for KOST. A refrag kill can answer multiple valid earlier eliminations; each death or kill is counted as traded at most once.</p></Explanation>
          <Explanation title="1vX clutches" summary="Win after becoming the last teammate alive."><p>The size is set when a player first becomes their team’s sole survivor, with one to five opponents alive. Count one clutch only if that player’s team ultimately wins the round, including objective-based wins. The player does not have to survive the winning finish.</p><div className="clutch-example"><strong>1v3 → 1v1 → round win</strong><span>One 1v3 clutch. No extra 1v2 or 1v1.</span></div><p>A lost round, a player who is already dead, or a sole survivor with zero opponents remaining does not qualify. Teamkills and suicides still affect who is alive.</p></Explanation>
          <Explanation title="Pivot kills / deaths" summary="Eliminations while tied or behind in players alive."><p>A pivot kill is an enemy elimination when the killer’s team has no more living players than the opposing team, immediately before the elimination. The victim receives the corresponding pivot death.</p></Explanation>
          <Explanation title="Untraded kills / deaths" summary="Eliminations that are not answered within the window."><p>An enemy kill is untraded when the original killer is not eliminated by the victim’s teammate within the trade window. An untraded death is a death that was not traded; deaths still include teamkills and suicides.</p></Explanation>
          <Explanation title="Attack / Defense & operators" summary="Round context and the operator actually played."><p>Side splits group rounds, kills and deaths by Attack or Defense. Operator usage records the operator selected when action phase begins, after attacker repick. Unresolved operators are omitted from usage counts, while the round remains in the player’s other statistics.</p></Explanation>
          <Explanation title="Technical details · event order" summary="Display history and v3’s verified inputs."><p>Historical display statistics use their preserved chronological elimination log. v3 separately requires positive serialized event offsets and exact finisher/victim/time/headshot parity for native opening and clutch order. No cumulative counter update is treated as an exact elimination timestamp.</p></Explanation>
        </div>
      </>}
    </section>
  </div>
}
