export type Team = {id:number;slug:string;name:string;primary_color:string;active:number;aliases:string[];maps:number;rounds:number;roster_count:number}
export type Stats = {appearance_role?:'roster'|'sub'|'mixed';status?:string;rating_rounds?:number;rating_maps?:number;kill_source_rounds?:Record<string,number>;slug:string;name:string;rating:number|null;rounds:number;maps:number;kills:number;deaths:number;kd:number|null;kd_diff:number;kpr:number;kost:number;srv:number;hs:number;opening_kills:number;opening_deaths:number;entry_diff:number;plants:number;disables:number;clutches:number;clutch_1v1:number;clutch_1v2:number;clutch_1v3:number;clutch_1v4:number;clutch_1v5:number;refrag_kills:number;deaths_traded:number;kills_traded:number;untraded_kills:number;untraded_deaths:number;pivot_kills:number;pivot_deaths:number;teamkills:number;operators:Record<string,Record<string,number>>;sides:Record<string,{rounds:number;kills:number;deaths:number;kd:number|null;kpr:number}>}
export type Match = {team_slug:string;team_name:string;id:string;series_id:string;season:string;opponent:string;date:string;week:string;notes:string;map:string;our_score:number;their_score:number;result:string;demo:boolean;rating?:number|null;rating_eligible?:boolean;rating_version?:string}
export type Season = {team?:Team;slug:string;name:string;demo:boolean;maps:number;wins:number;rounds_won:number;rounds:number;players:Stats[];sub_players?:Stats[];matches:Match[];roster?:{slug:string;name:string;status:string}[]}
export type Index = {program:{name:string;short_name:string;accent?:string};teams:Team[];team:{name:string;short_name:string;accent:string};generated_at?:string;active_season:string|null;seasons:{slug:string;name:string;start_date?:string;end_date?:string}[];players:{slug:string;name:string;status:string;memberships:{team_slug:string;team_name:string;start_date:string;end_date:string|null}[]}[]}

export type SeriesPoint={id:string;series_id:string;team_slug:string;team_name:string;season:string;season_name:string;opponent:string;date:string;recorded_maps:{count:number;wins:number;losses:number};rating_version:string;rating:number|null;rating_rounds:number;rating_maps:number;rounds:number;maps:number}
export type Series={id:string;series_id:string;team_slug:string;team_name:string;season:string;season_name:string;opponent:string;date:string;week:string;notes:string;demo:boolean;recorded_maps:{count:number;wins:number;losses:number};rounds:number;rating_version:string;maps:Match[];players:Stats[]}
export type Highlight={player_slug:string;player_name:string;labels:string[];emphasis:'strong'|'notable'|'objective'}
export type PublicRound={number:number;side:string;site:string;result:string;highlights?:Highlight[]}
