import {useEffect,useState} from 'react'
import type {Match,Team} from './publicTypes'
import {ratingHistory,decimal} from './presentation'
import {teamTheme} from './theme'

export function RatingTrend({matches,teams}:{matches:Match[];teams:Team[]}){
 const points=ratingHistory(matches),[active,setActive]=useState<string|null>(null)
 useEffect(()=>setActive(null),[matches])
 const selected=points.find(m=>m.id===active)||points.at(-1)
 const values=points.map(m=>m.rating!),min=Math.min(.8,...values)-.08,max=Math.max(1.2,...values)+.08
 const x=(i:number)=>points.length===1?360:58+i*604/(points.length-1),y=(rating:number)=>180-(rating-min)*140/(max-min)
 return <section className="panel rating-trend" aria-label="Player map Rating trend"><div className="trend-heading"><div><span className="eyebrow">MAP BY MAP</span><h2>Rating trend</h2></div><span className="section-aside">{points.length} of {matches.length} maps eligible</span></div><p>Published v3 map Ratings, in chronological order. Unrated maps are omitted.</p>{points.length? <><svg className="trend-svg" viewBox="0 0 720 215" role="group" aria-label="Map Ratings, oldest to newest"><text x="8" y="48">{decimal(max)}</text><text x="8" y="183">{decimal(min)}</text><line x1="58" x2="662" y1={y(1)} y2={y(1)} className="trend-reference"/><text x="673" y={y(1)+4}>1.00</text><polyline className="trend-line" points={points.map((m,i)=>`${x(i)},${y(m.rating!)}`).join(' ')}/>{points.map((m,i)=><g key={m.id} style={teamTheme(teams.find(t=>t.slug===m.team_slug)?.primary_color||'#0058A4')}><circle className="trend-point" cx={x(i)} cy={y(m.rating!)} r={m.id===selected?.id?7:5} tabIndex={0} role="button" aria-label={`${m.date}, ${m.map}, vs ${m.opponent}, ${m.result} ${m.our_score}-${m.their_score}, Rating ${decimal(m.rating!)}, ${m.team_name}`} aria-pressed={m.id===selected?.id} onMouseEnter={()=>setActive(m.id)} onFocus={()=>setActive(m.id)} onClick={()=>setActive(m.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setActive(m.id)}if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const n=Math.max(0,Math.min(points.length-1,i+(e.key==='ArrowRight'?1:-1)));setActive(points[n].id);const circles=e.currentTarget.ownerSVGElement?.querySelectorAll<SVGCircleElement>('.trend-point');circles?.[n].focus()}}}/></g>)}<text x="58" y="209">{points[0].date}</text><text x="662" y="209" textAnchor="end">{points.at(-1)?.date}</text></svg>{selected&&<div className="trend-detail" role="status" style={teamTheme(teams.find(t=>t.slug===selected.team_slug)?.primary_color||'#0058A4')}><span className="team-chip">{selected.team_name}</span><span>{selected.date} · vs {selected.opponent} · {selected.map}</span><span>{selected.result} · {selected.our_score}–{selected.their_score}</span><strong>Rating {decimal(selected.rating!)}</strong></div>}<div className="recent-rating"><span>Recent Rating</span>{points.slice(-5).map(m=><button type="button" key={m.id} onClick={()=>setActive(m.id)} aria-label={`Show ${m.map} on ${m.date}, Rating ${decimal(m.rating!)}`} aria-pressed={selected?.id===m.id}>{decimal(m.rating!)}</button>)}</div></>:<div className="empty">No eligible map Ratings yet.</div>}</section>
}
