export function RatingFormula({ version }: { version: string }) {
  if (version === 'siege_style_v3') {
    return <section className="panel formula"><span className="eyebrow">RATING / SIEGE_STYLE_V3</span><h2>Validated credited-count and native-order Rating</h2><p>Rating uses Ubisoft credited kills, extra credited multikills, verified core plants/disables, corrected KOST Kill, survival, native finisher opening differential and successful clutches weighted by X(X+1)/2. Trade differential and the KOST traded-death flag retain the frozen legacy 8-second policy; precise credited-owner trade timing remains unresolved. Only whole maps with complete credited, objective and native event evidence contribute. Rating coverage can be smaller than the displayed historical rounds: player pages and leaderboard Rating tooltips show eligible rounds/maps. Displayed Entry and 1vX preserve legacy event chronology; v3 independently verifies native chronology for its inputs. Historical v2 inputs and coefficients remain preserved. This is not an official SiegeGG or Ubisoft formula.</p><code>Rating = 0.073737 + 0.589345 KPR − 0.172399 teamkill rate + 0.220248 extra multikill rate + 0.153147 native finisher opening differential rate + 0.245261 triangular clutch rate + 0.459181 KOST + 0.488176 survival + 0.096126 trade differential rate + 0.450201 objective rate</code><p>Frozen before evaluation on APAC North Stage 1: 110 player-map observations across 11 maps and 8 rosters; MAE 0.03036, 81.82% within 0.05. Development used 988 observations and 10 whole-event folds. Larger independent samples and rare clutch sizes remain future validation work.</p></section>
  }
  if (version === 'siege_style_v2') {
    return <section className="panel formula"><span className="eyebrow">RATING / SIEGE_STYLE_V2</span><h2>Independent Siege-style Rating</h2><p>Rating combines kills, teamkills, extra kills in multikill rounds, opening differential, successful 1vX clutches, KOST, survival, and trade differential. It is calibrated against professional player-map ratings. Displayed kills, multikills and KOST use validated credited counts on supported whole maps; objectives include supported actor corrections. For upgraded historical maps, Rating retains the original v2 input snapshot, so its kill, multikill and KOST inputs can differ from displayed statistics. The direct objective coefficient remains zero. Incomplete maps with manual final K/D are excluded; season and career Rating use complete eligible maps only. This is not an official SiegeGG or Ubisoft formula.</p><code>Rating = 0.072957 + 0.561745 KPR − 0.203330 teamkill rate + 0.227137 extra multikill rate + 0.146293 opening differential rate + 0.668883 clutch rate + 0.503157 KOST + 0.490045 survival + 0.141805 trade differential rate</code></section>
  }
  return <section className="panel formula"><span className="eyebrow">RATING / COLLEGIATE_V1</span><h2>Collegiate composite performance</h2><p>Rating combines per round kills, pivot kills, untraded kills, deaths, pivot deaths, untraded deaths, objectives, KOST, and traded kill/death ratios with fixed weights. Incomplete maps with manual final K/D are excluded; season and career Rating use complete eligible maps only. This is neither official Ubisoft EPS nor official SiegeGG Rating.</p><code>Rating = (0.3110 KPR + 0.6037 pivot KPR + 0.5408 untraded KPR − 0.4894 DPR − 0.5966 pivot DPR − 0.6596 untraded DPR + 0.1929 objective rate + 0.3320 KOST − 0.2464 traded kill ratio + 0.1564 traded death ratio) × 1.0698 + 1</code></section>
}
